name = "telegram-store-backend"
main = "build/worker.mjs"
compatibility_date = "2026-06-19"

[[d1_databases]]
binding = "DB"
database_name = "tg-store-db"
database_id = "baf6cdd2-5c2a-41d5-b217-0edbcf89c375"
