name = "telegram-store-backend"
main = "build/app.wasm"
compatibility_date = "2026-06-19"

[build]
command = "tinygo build -o build/app.wasm -target wasm main.go"

[[d1_databases]]
binding = "DB"
database_name = "tg-store-db"
database_id = "baf6cdd2-5c2a-41d5-b217-0edbcf89c375"
